### ISSUE TITLE
F5 shortcut not working.Save works but not compile.

### ISSUE THREAD

**Issue by tomas0430** [martineausimon/vim-lilypond-suite#1]
Running it  from command  :MakeLilyPond no success. Does not compile. Should I set up some variables for it to work?

**Comment by martineausimon** [comment]
Can you try just with `:!lilypond %` ?

**Comment by tomas0430** [comment]
it compiles when I run ":!lilypond % ,but it puts compiled file in a home directory not in working one

**Comment by martineausimon** [comment]
Do you open your file directly in your working directory or with `nvim path/to/file.ly` ?

**Comment by tomas0430** [comment]
I open in workin directory like "nvim ConfirmationEb.ly". F5 shortcut works but not on every file. I can't find a clue why.

**Comment by tomas0430** [comment]
Sorry. Everything is working as supose to. :D . Have no ideo why it didn't work before. Thanks for your quick response

**Comment by martineausimon** [comment]
I think it can be a problem with a file name containing spaces, i need to fix it

**Comment by martineausimon** [comment]
It should work new with filenames containing spaces

**Comment by martineausimon** [comment]
Ok it should work now !
